
# profiles.yml - Database Configuration for DBT

job_intelligent:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'duckdb.db'
      threads: 4
      timeout_seconds: 300

    prod:
      type: duckdb
      path: 'job_intelligent_prod.db'
      threads: 4
      timeout_seconds: 600
